# Generated by Django 4.0.4 on 2022-04-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_remove_sound_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='audio_file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sound',
            name='audio_file3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
