# Generated by Django 4.0.4 on 2022-04-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0004_sound_audio_file4_sound_audio_file5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='audio_file4',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='audio_file5',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='audio_file6',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='audio_file7',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='audio_file8',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='audio_file9',
        ),
    ]
